DOC: add a skeleton and workflow for docs building
nsls2-conda-envs/conda-pack-template pull request #72
Opened 2022-08-30 14:41 UTC by mrakitin

WIP

2022-09-02 15:54 UTC, gwbischof approved these changes

2022-09-02 22:00 UTC, JunAishima requested changes
Should this documentation be used to replace the README.md file or replace that as well? that file has been outdated for a while.

Otherwise, this will be a valuable resource for anybody who wants to understand how this conda environment building system works, whether to add a config to build their own environment or to update the system.

2022-09-02 22:00 UTC, JunAishima commented on .github/workflows/docs.yml
> +      - name: Build Docs
looks like the docs are built - are they meant to be published as well?

2022-09-02 22:00 UTC, JunAishima commented on docs/source/index.rst
> +
did you want to mention zenodo or other extra options (in this case, for publishing)?

2022-09-06 14:11 UTC, mrakitin commented on docs/source/conf.py
> +author = "nsls2-conda-envs"
Good point, I'll correct it. The values were added automatically by the cookiecutter.

2022-09-06 14:12 UTC, mrakitin commented on docs/source/index.rst
> +  specify the command to run in Docker after conda environment installation
I'll add a couple of examples.

2022-09-06 14:13 UTC, mrakitin commented on .github/workflows/docs.yml
> +      - name: Build Docs
Yes, I'll address it via a separate PR -- just wanted to make sure we cover the basics first.

2022-09-06 14:15 UTC, mrakitin commented on docs/source/index.rst
> +
Zenodo publishing is pretty experimental for now in this repo. We need to update the code in `zenodo.py` to allow publishing reliably. I'll need to combine the code with https://github.com/nsls2-conda-envs/playground/blob/ci-upload-nsls2-collection-2022-2.4/test-upload.py. Once the code is added, we can update the documentation.

2022-09-19 21:27 UTC, JunAishima approved these changes

2022-09-19 21:33 UTC, mrakitin commented
I changed the sphinx theme to https://cloud-sptheme.readthedocs.io/en/latest/ (similar to https://github.com/NSLS-II/sirepo-bluesky/pull/80). The built docs will look like:

![image](https://user-images.githubusercontent.com/13209176/191123371-6b5c91b0-acd7-448a-ab76-3df7f6573e9e.png)

2022-09-19 21:36 UTC, mrakitin commented
@JunAishima, @gwbischof, ready for your review. The built docs are available in https://github.com/nsls2-conda-envs/conda-pack-template/actions/runs/3085767320 if you'd like to check the rendered version.

2022-09-22 15:10 UTC, mrakitin commented
OK, I am going to merge it given one review (that I dismissed to solve the CI/STY issues.)

2022-09-22 15:10 UTC, merged

2022-10-05 02:53 UTC, mrakitin commented
The docs are live now: https://nsls2-conda-envs.github.io/conda-pack-template (implemented via https://github.com/nsls2-conda-envs/conda-pack-template/commit/1ae01fa34c1a666e089e539ed92ba8f8e0184b28 and the repo settings).

The https://github.com/nsls2-conda-envs/conda-pack-template/commit/0ff2ad364ad85d2b96ebea6cf2c8b6eb286b75e3 commit updates the `README.md` file.

The next step is to rename the repo and apply the changes to all env-repos.